### PR TITLE
T-1284: rm `EXPLORER` flash on load

### PR DESCRIPTION
**Pull request by pmillspaugh**
1. rm `EXPLORER` sidebar flash on login and signup
2. rm commands that open the file explorer*
    1. rm `View: Show Explorer` command
    2. rm `Files: Focus on Files Explorer` command
    3. rm `Explorer: Focus on Folders View`
    4. rm `Explorer: Focus on Open Editors View`
    5. rm `Refresh Explorer`
    6. rm `Collapse Folders in Explorer`

_*I left the file outline and timeline there for now_

## Before

https://github.com/user-attachments/assets/3051f902-9243-4fc4-8eb0-7706368638c7

## After

https://github.com/user-attachments/assets/8fce27a9-123a-4fbd-9fbd-6f6d43d0376a

### CODE REVIEW

**Comment by pmillspaugh** [comment]
@juancampa I have been poking around for other ways to open the file explorer. I found and removed a handful, but there could be more, so we can all keep an eye out. 

I also learned some neat things by trying every option in the right-click context menu on an open file in the editor (in particular, `Source Action...` has some useful actions like organizing imports and removing unused imports!).

**Comment by iamseeley** [comment]
Hoorah! 

It kinda hurts to see the blank screen for so long 🥲 I wonder what we can do to improve the time to interactive. 

I think having the site M logo loading state, the M watermark, and then the spinny loaders (in the gaze panels) is janky. 

Maybe at some point we can have one loading state. Either M logo pulsing or the watermark, and make it so the gaze panels take a progressive loading approach with more filler UI/skeletons ?

**Comment by juancampa** [comment]
> I think having the site M logo loading state, the M watermark, and then the spinny loaders (in the gaze panels) is janky.

Totally agree. 6 seconds in that video! Although in production is more like 1~2s

> Either M logo pulsing or the watermark,

I think the pulsating M logo is the way to go. I have an idea on how to do that easily. Will try it and report back.

**Comment by juancampa** [comment]
> in particular, `Source Action...` has some useful actions like organizing imports and removing unused imports!

Good to know. I just tried it in Rust but "No actions available" I was hoping to find a "Remove unused use statements" 😞

> I have been poking around for other ways to open the file explorer.

I couldn't find it either. It's possible that I got confused and thought that `Find all references` opened the explorer but, nope, it opens its own separate panel and the `X` takes you back 👍

**Review by juancampa — APPROVED** [review]
Looks great! Thanks for investigating all the possible cases

**Comment by pmillspaugh** [comment]
@juancampa @iamseeley re the loading state:

Juan and I [briefly discussed](https://github.com/membrane-io/mnode/pull/387#discussion_r1890735278) moving the IDE to `ide.membrane.io` because global styles conflict, and maintenance is starting to get trickier. I am now going down that road and can take a look at loading state (or copy in the solution Juan has in mind)

**Pull request merged**
